# Generated by Django 5.2 on 2025-05-05 00:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tomegah_acte', '0001_initial'),
        ('tomegah_specialite', '0001_initial'),
        ('tomegah_type_acte', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='acte',
            name='Specialite',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tomegah_specialite.specialite'),
        ),
        migrations.AddField(
            model_name='acte',
            name='type_acte',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tomegah_type_acte.typeacte'),
        ),
    ]
