# Generated by Django 5.2 on 2025-05-11 18:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tomegah_consultation', '0002_consultation_agepatient_and_more'),
        ('tomegah_medecin', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ordonnance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_ordonnance', models.CharField(max_length=20, unique=True)),
                ('date_ordonnance', models.DateField()),
                ('consultation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tomegah_consultation.consultation')),
                ('medecin', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='tomegah_medecin.medecin')),
            ],
        ),
    ]
