# Generated by Django 5.2 on 2025-05-04 03:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tomegah_personne', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('personne_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='tomegah_personne.personne')),
                ('dateenreg', models.DateField(auto_now_add=True)),
            ],
            bases=('tomegah_personne.personne',),
        ),
    ]
