# Generated by Django 5.2 on 2025-05-10 16:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tomegah_consultation', '0002_consultation_agepatient_and_more'),
        ('tomegah_medecin', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Facture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_facture', models.CharField(max_length=20, unique=True)),
                ('typefacture', models.CharField(max_length=100)),
                ('dateenreg_facture', models.DateField()),
                ('datepaiement_facture', models.DateField(blank=True, null=True)),
                ('montant_facture', models.IntegerField()),
                ('montant_payefacture', models.IntegerField()),
                ('reste_a_payer', models.IntegerField()),
                ('etat_facture', models.CharField(choices=[('Im', 'Impayée'), ('pA', 'Payée')], default='Im', max_length=3)),
                ('consultation', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='tomegah_consultation.consultation')),
                ('medecin', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='tomegah_medecin.medecin')),
                ('utilisateur', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
