# Generated by Django 5.2 on 2025-05-10 21:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tomegah_facture', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='facture',
            name='reste_a_payer',
        ),
    ]
