# Generated by Django 5.2 on 2025-05-10 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tomegah_facture', '0002_remove_facture_reste_a_payer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facture',
            name='etat_facture',
            field=models.CharField(choices=[('Im', 'Impayée'), ('pA', 'Payée'), ('PA', 'Partiellement payée')], default='Im', max_length=3),
        ),
    ]
