# Generated by Django 5.2 on 2025-05-11 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tomegah_facture', '0003_alter_facture_etat_facture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facture',
            name='etat_facture',
            field=models.CharField(choices=[('Im', 'Impayée'), ('Payée', 'Payée'), ('Partie. payée', 'Partiellement payée')], default='Im', max_length=15),
        ),
    ]
