# Generated by Django 5.2 on 2025-05-05 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tomegah_medecin', '0001_initial'),
        ('tomegah_specialite', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='medecin',
            name='specialites',
            field=models.ManyToManyField(blank=True, through='tomegah_specialite.AffecterSpecialite', to='tomegah_specialite.specialite'),
        ),
    ]
