# Generated by Django 5.2 on 2025-05-11 18:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tomegah_medicament', '0001_initial'),
        ('tomegah_ordonnance', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrdonnanceDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_ordonnancedetail', models.CharField(max_length=20, unique=True)),
                ('posologie_medicament', models.CharField(max_length=1000)),
                ('medicament', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='tomegah_medicament.medicament')),
                ('ordonnance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='tomegah_ordonnance.ordonnance')),
            ],
        ),
    ]
