# Generated by Django 5.2 on 2025-05-05 04:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tomegah_acte', '0002_initial'),
        ('tomegah_medecin', '0002_initial'),
        ('tomegah_patient', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Consultation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codeconsultation', models.CharField(max_length=10, unique=True)),
                ('dateconsultation', models.DateField()),
                ('datefinvaliditeconsultation', models.DateField()),
                ('acte', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tomegah_acte.acte')),
                ('medecin', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='tomegah_medecin.medecin')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tomegah_patient.patient')),
                ('utilisateur', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
