# Generated by Django 5.2 on 2025-05-09 22:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tomegah_acte', '0002_initial'),
        ('tomegah_consultation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultation',
            name='agePatient',
            field=models.IntegerField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='consultation',
            name='temperaturePatient',
            field=models.DecimalField(decimal_places=2, default=None, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='consultation',
            name='acte',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='tomegah_acte.acte'),
        ),
    ]
