# Generated by Django 5.2 on 2025-05-10 16:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tomegah_acte', '0002_initial'),
        ('tomegah_facture', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FactureDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_detailfacture', models.CharField(max_length=20, unique=True)),
                ('montant_facturedetail', models.IntegerField()),
                ('acte', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tomegah_acte.acte')),
                ('facture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='tomegah_facture.facture')),
            ],
        ),
    ]
