# Generated by Django 5.2 on 2025-05-04 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Personne',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, unique=True)),
                ('nom', models.CharField(max_length=50)),
                ('prenom', models.CharField(max_length=100)),
                ('datenaissance', models.DateField()),
                ('civilite', models.CharField(choices=[('M', 'Monsieur'), ('MM', 'Madame'), ('ML', 'Mademoiselle')], max_length=3)),
            ],
        ),
    ]
