# Generated by Django 5.2 on 2025-05-05 00:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tomegah_medecin', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Specialite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, unique=True)),
                ('libelle', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='AffecterSpecialite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_affectation', models.DateField(auto_now_add=True)),
                ('medecin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tomegah_medecin.medecin')),
                ('specialite', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tomegah_specialite.specialite')),
            ],
            options={
                'unique_together': {('medecin', 'specialite')},
            },
        ),
    ]
