# Generated by Django 5.2 on 2025-05-11 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tomegah_medicament', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicament',
            name='dosage',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='medicament',
            name='forme',
            field=models.CharField(choices=[('Comprimé', 'Comprimé'), ('Sirop', 'Sirop'), ('Injection', 'Injection'), ('Pommade', 'Pommade'), ('Gélule', 'Gélule'), ('Spray', 'Spray')], default='Comprimé', max_length=20),
        ),
        migrations.AddField(
            model_name='medicament',
            name='voie_administration',
            field=models.CharField(choices=[('Orale', 'Orale'), ('Cutanée', 'Cutanée'), ('Intraveineuse', 'Intraveineuse'), ('Intramusculaire', 'Intramusculaire'), ('Nasale', 'Nasale'), ('Oculaire', 'Oculaire')], default='Orale', max_length=30),
        ),
    ]
